#!/usr/bin/env bash
set -euo pipefail

thirds_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${thirds_dir}/.." && pwd)"

# shellcheck source=versions.env
source "${thirds_dir}/versions.env"

cache_dir="${thirds_dir}/cache"
source_dir="${thirds_dir}/source"
build_dir="${thirds_dir}/build"
toolchain_dir="${thirds_dir}/toolchain"
sdk_dir="${thirds_dir}/psn00bsdk"
jobs="$(sysctl -n hw.logicalcpu 2>/dev/null || echo 4)"
mode="install"

usage() {
    echo "Usage: $0 [--check] [--jobs N]"
    echo "  --check   Validate the host and installed toolchain without changing files."
    echo "  --jobs N  Parallel build jobs (default: ${jobs})."
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --check)
            mode="check"
            shift
            ;;
        --jobs)
            [[ $# -ge 2 ]] || { usage >&2; exit 2; }
            jobs="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            usage >&2
            exit 2
            ;;
    esac
done

if [[ "$(uname -s)" != "Darwin" ]]; then
    echo "This bootstrap currently supports macOS only; Linux and Windows are tracked in ROADMAP.md." >&2
    exit 1
fi

if ! xcode-select -p >/dev/null 2>&1; then
    echo "Install Apple's Command Line Tools with: xcode-select --install" >&2
    exit 1
fi

if ! command -v brew >/dev/null 2>&1; then
    echo "Homebrew is required for host-only build dependencies: https://brew.sh" >&2
    exit 1
fi

write_environment() {
    local temporary="${thirds_dir}/env.sh.tmp"
    {
        echo '# Generated by thirds/setup_macos.sh. Do not edit.'
        printf 'export PSXE_TOOLCHAIN=%q\n' "${toolchain_dir}"
        printf 'export PSN00BSDK_LIBS=%q\n' "${sdk_dir}/lib/libpsn00b"
        printf 'export PATH=%q:$PATH\n' "${sdk_dir}/bin:${toolchain_dir}/bin"
    } > "${temporary}"
    mv "${temporary}" "${thirds_dir}/env.sh"
}

check_installation() {
    local failed=0
    local command_name
    for command_name in cmake ninja git curl make shasum; do
        if ! command -v "${command_name}" >/dev/null 2>&1; then
            echo "missing host command: ${command_name}" >&2
            failed=1
        fi
    done
    if [[ ! -x "${toolchain_dir}/bin/mipsel-none-elf-gcc" ]]; then
        echo "missing target compiler: ${toolchain_dir}/bin/mipsel-none-elf-gcc" >&2
        failed=1
    fi
    if [[ ! -f "${sdk_dir}/lib/libpsn00b/cmake/sdk.cmake" ]]; then
        echo "missing SDK: ${sdk_dir}/lib/libpsn00b/cmake/sdk.cmake" >&2
        failed=1
    fi
    if [[ ! -x "${sdk_dir}/bin/mkpsxiso" ]]; then
        echo "missing disc tool: ${sdk_dir}/bin/mkpsxiso" >&2
        failed=1
    fi
    if [[ "${failed}" -ne 0 ]]; then
        return 1
    fi
    "${toolchain_dir}/bin/mipsel-none-elf-gcc" --version | head -n 1
    cmake --version | head -n 1
    echo "PSn00bSDK root: ${sdk_dir}"
}

if [[ "${mode}" == "check" ]]; then
    check_installation
    exit
fi

host_packages=(cmake ninja gmp libmpc mpfr gnu-sed texinfo xz)
missing_packages=()
for package in "${host_packages[@]}"; do
    if ! brew list --versions "${package}" >/dev/null 2>&1; then
        missing_packages+=("${package}")
    fi
done
if [[ "${#missing_packages[@]}" -gt 0 ]]; then
    echo "Installing missing host build dependencies with Homebrew..."
    brew install "${missing_packages[@]}"
else
    echo "Homebrew host build dependencies are already installed."
fi

mkdir -p "${cache_dir}" "${source_dir}" "${build_dir}" "${toolchain_dir}" "${sdk_dir}"

download_and_verify() {
    local url="$1"
    local destination="$2"
    local expected="$3"
    local actual
    if [[ ! -f "${destination}" ]]; then
        curl --fail --location --retry 3 --output "${destination}.part" "${url}"
        mv "${destination}.part" "${destination}"
    fi
    actual="$(shasum -a 256 "${destination}" | awk '{print $1}')"
    if [[ "${actual}" != "${expected}" ]]; then
        echo "Checksum mismatch for ${destination}" >&2
        echo "expected ${expected}" >&2
        echo "actual   ${actual}" >&2
        exit 1
    fi
}

binutils_archive="${cache_dir}/binutils-${BINUTILS_VERSION}.tar.gz"
gcc_archive="${cache_dir}/gcc-${GCC_VERSION}.tar.xz"
download_and_verify \
    "https://ftpmirror.gnu.org/gnu/binutils/binutils-${BINUTILS_VERSION}.tar.gz" \
    "${binutils_archive}" \
    "${BINUTILS_SHA256}"
download_and_verify \
    "https://ftpmirror.gnu.org/gnu/gcc/gcc-${GCC_VERSION}/gcc-${GCC_VERSION}.tar.xz" \
    "${gcc_archive}" \
    "${GCC_SHA256}"

if [[ ! -x "${source_dir}/binutils-${BINUTILS_VERSION}/configure" ]]; then
    /usr/bin/tar -xzf "${binutils_archive}" -C "${source_dir}"
fi
if [[ ! -x "${toolchain_dir}/bin/mipsel-none-elf-as" ]]; then
    mkdir -p "${build_dir}/binutils"
    pushd "${build_dir}/binutils" >/dev/null
    "${source_dir}/binutils-${BINUTILS_VERSION}/configure" \
        --target=mipsel-none-elf \
        --prefix="${toolchain_dir}" \
        --disable-docs \
        --disable-multilib \
        --disable-nls \
        --disable-werror \
        --with-float=soft
    make -j "${jobs}"
    make install-strip
    popd >/dev/null
fi

if [[ ! -f "${source_dir}/gcc-${GCC_VERSION}/move-if-change" ]]; then
    /usr/bin/tar -xJf "${gcc_archive}" -C "${source_dir}"
fi
gcc_runtime="${toolchain_dir}/lib/gcc/mipsel-none-elf/${GCC_VERSION}/libgcc.a"
cpp_runtime="${toolchain_dir}/mipsel-none-elf/lib/libstdc++.a"
if [[ ! -x "${toolchain_dir}/bin/mipsel-none-elf-gcc" ||
      ! -f "${gcc_runtime}" || ! -f "${cpp_runtime}" ]]; then
    mkdir -p "${build_dir}/gcc"
    export PATH="$(brew --prefix gnu-sed)/libexec/gnubin:${toolchain_dir}/bin:${PATH}"
    pushd "${build_dir}/gcc" >/dev/null
    "${source_dir}/gcc-${GCC_VERSION}/configure" \
        --target=mipsel-none-elf \
        --prefix="${toolchain_dir}" \
        --with-gmp="$(brew --prefix gmp)" \
        --with-mpfr="$(brew --prefix mpfr)" \
        --with-mpc="$(brew --prefix libmpc)" \
        --with-as="${toolchain_dir}/bin/mipsel-none-elf-as" \
        --with-ld="${toolchain_dir}/bin/mipsel-none-elf-ld" \
        --with-arch=mips1 \
        --with-tune=mips1 \
        --with-float=soft \
        --with-endian=little \
        --without-isl \
        --without-headers \
        --disable-analyzer \
        --disable-multilib \
        --disable-nls \
        --disable-threads \
        --disable-shared \
        --disable-libssp \
        --disable-libstdcxx-pch \
        --disable-libgomp \
        --disable-werror \
        --disable-hosted-libstdcxx \
        --enable-languages=c,c++
    make -j "${jobs}" all-gcc
    make install-strip-gcc
    make -j "${jobs}" all-target-libgcc
    make install-strip-target-libgcc
    make -j "${jobs}" all-target-libstdc++-v3
    make install-strip-target-libstdc++-v3
    popd >/dev/null
fi

sdk_source="${source_dir}/psn00bsdk"
if [[ ! -d "${sdk_source}/.git" ]]; then
    git clone https://github.com/Lameguy64/PSn00bSDK.git "${sdk_source}"
fi
git -C "${sdk_source}" fetch --quiet origin "${PSN00BSDK_COMMIT}"
git -C "${sdk_source}" checkout --quiet --detach "${PSN00BSDK_COMMIT}"
git -C "${sdk_source}" submodule update --init --recursive

export PATH="${toolchain_dir}/bin:${PATH}"
# GCC 15 and newer default to C23, where an empty parameter list means no
# parameters. This pinned SDK still uses the pre-C23 unspecified-arguments form
# for BIOS callback thunks, so build it in its intended GNU C17 dialect.
export CFLAGS="${CFLAGS:+${CFLAGS} }-std=gnu17"
cmake -S "${sdk_source}" -B "${build_dir}/psn00bsdk" -G Ninja \
    -DCMAKE_INSTALL_PREFIX="${sdk_dir}" \
    -DPSN00BSDK_TC="${toolchain_dir}" \
    -DSKIP_EXAMPLES=ON
cmake --build "${build_dir}/psn00bsdk" --parallel "${jobs}"
cmake --install "${build_dir}/psn00bsdk"

write_environment
check_installation
echo "Toolchain ready. Build the engine with: ${repo_root}/build.sh"
